name: Docker Image CI/CD

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "bun.lockb"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "tests/**"
      - "package.json"
      - "bun.lockb"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed"

      # Add Bun to PATH
      - name: Set up Bun
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run tests
      - name: Run Bun tests
        run: ENV=test bun test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/asam-task:latest
